2024-10-14 16:04:45,565 ERROR: Task completed with error: 
paragraph text "<para><p>Patient's Name: <strong><em>_</strong><strong></em><em></strong><strong></em><em></strong></em>_</para>" caused exception Parse error: saw </strong> instead of expected </em> [in /Users/didntforeseethat/Revised_PAR/app.py:187]
2024-10-14 16:04:51,542 INFO: Processing route accessed [in /Users/didntforeseethat/Revised_PAR/app.py:164]
2024-10-14 16:04:51,560 INFO: Task state: SUCCESS [in /Users/didntforeseethat/Revised_PAR/app.py:171]
2024-10-14 16:04:51,560 INFO: Task 0f9b84a9-9793-4a0b-b829-7e178e279d1e completed successfully [in /Users/didntforeseethat/Revised_PAR/app.py:179]
2024-10-14 16:04:51,560 ERROR: Task completed with error: 
paragraph text "<para><p>Patient's Name: <strong><em>_</strong><strong></em><em></strong><strong></em><em></strong></em>_</para>" caused exception Parse error: saw </strong> instead of expected </em> [in /Users/didntforeseethat/Revised_PAR/app.py:187]
2024-10-14 16:04:57,540 INFO: Processing route accessed [in /Users/didntforeseethat/Revised_PAR/app.py:164]
2024-10-14 16:04:57,554 INFO: Task state: SUCCESS [in /Users/didntforeseethat/Revised_PAR/app.py:171]
2024-10-14 16:04:57,554 INFO: Task 0f9b84a9-9793-4a0b-b829-7e178e279d1e completed successfully [in /Users/didntforeseethat/Revised_PAR/app.py:179]
2024-10-14 16:04:57,554 ERROR: Task completed with error: 
paragraph text "<para><p>Patient's Name: <strong><em>_</strong><strong></em><em></strong><strong></em><em></strong></em>_</para>" caused exception Parse error: saw </strong> instead of expected </em> [in /Users/didntforeseethat/Revised_PAR/app.py:187]
2024-10-14 16:05:03,536 INFO: Processing route accessed [in /Users/didntforeseethat/Revised_PAR/app.py:164]
2024-10-14 16:05:03,540 INFO: Task state: SUCCESS [in /Users/didntforeseethat/Revised_PAR/app.py:171]
2024-10-14 16:05:03,541 INFO: Task 0f9b84a9-9793-4a0b-b829-7e178e279d1e completed successfully [in /Users/didntforeseethat/Revised_PAR/app.py:179]
2024-10-14 16:05:03,541 ERROR: Task completed with error: 
paragraph text "<para><p>Patient's Name: <strong><em>_</strong><strong></em><em></strong><strong></em><em></strong></em>_</para>" caused exception Parse error: saw </strong> instead of expected </em> [in /Users/didntforeseethat/Revised_PAR/app.py:187]
2024-10-14 16:05:09,545 INFO: Processing route accessed [in /Users/didntforeseethat/Revised_PAR/app.py:164]
2024-10-14 16:05:09,559 INFO: Task state: SUCCESS [in /Users/didntforeseethat/Revised_PAR/app.py:171]
2024-10-14 16:05:09,559 INFO: Task 0f9b84a9-9793-4a0b-b829-7e178e279d1e completed successfully [in /Users/didntforeseethat/Revised_PAR/app.py:179]
2024-10-14 16:05:09,560 ERROR: Task completed with error: 
paragraph text "<para><p>Patient's Name: <strong><em>_</strong><strong></em><em></strong><strong></em><em></strong></em>_</para>" caused exception Parse error: saw </strong> instead of expected </em> [in /Users/didntforeseethat/Revised_PAR/app.py:187]
2024-10-14 16:05:15,542 INFO: Processing route accessed [in /Users/didntforeseethat/Revised_PAR/app.py:164]
2024-10-14 16:05:15,554 INFO: Task state: SUCCESS [in /Users/didntforeseethat/Revised_PAR/app.py:171]
2024-10-14 16:05:15,554 INFO: Task 0f9b84a9-9793-4a0b-b829-7e178e279d1e completed successfully [in /Users/didntforeseethat/Revised_PAR/app.py:179]
2024-10-14 16:05:15,555 ERROR: Task completed with error: 
paragraph text "<para><p>Patient's Name: <strong><em>_</strong><strong></em><em></strong><strong></em><em></strong></em>_</para>" caused exception Parse error: saw </strong> instead of expected </em> [in /Users/didntforeseethat/Revised_PAR/app.py:187]
2024-10-14 16:05:21,542 INFO: Processing route accessed [in /Users/didntforeseethat/Revised_PAR/app.py:164]
2024-10-14 16:05:21,555 INFO: Task state: SUCCESS [in /Users/didntforeseethat/Revised_PAR/app.py:171]
2024-10-14 16:05:21,555 INFO: Task 0f9b84a9-9793-4a0b-b829-7e178e279d1e completed successfully [in /Users/didntforeseethat/Revised_PAR/app.py:179]
2024-10-14 16:05:21,555 ERROR: Task completed with error: 
paragraph text "<para><p>Patient's Name: <strong><em>_</strong><strong></em><em></strong><strong></em><em></strong></em>_</para>" caused exception Parse error: saw </strong> instead of expected </em> [in /Users/didntforeseethat/Revised_PAR/app.py:187]
2024-10-14 16:05:27,543 INFO: Processing route accessed [in /Users/didntforeseethat/Revised_PAR/app.py:164]
2024-10-14 16:05:27,556 INFO: Task state: SUCCESS [in /Users/didntforeseethat/Revised_PAR/app.py:171]
2024-10-14 16:05:27,556 INFO: Task 0f9b84a9-9793-4a0b-b829-7e178e279d1e completed successfully [in /Users/didntforeseethat/Revised_PAR/app.py:179]
2024-10-14 16:05:27,556 ERROR: Task completed with error: 
paragraph text "<para><p>Patient's Name: <strong><em>_</strong><strong></em><em></strong><strong></em><em></strong></em>_</para>" caused exception Parse error: saw </strong> instead of expected </em> [in /Users/didntforeseethat/Revised_PAR/app.py:187]
2024-10-14 16:05:33,545 INFO: Processing route accessed [in /Users/didntforeseethat/Revised_PAR/app.py:164]
2024-10-14 16:05:33,559 INFO: Task state: SUCCESS [in /Users/didntforeseethat/Revised_PAR/app.py:171]
2024-10-14 16:05:33,559 INFO: Task 0f9b84a9-9793-4a0b-b829-7e178e279d1e completed successfully [in /Users/didntforeseethat/Revised_PAR/app.py:179]
2024-10-14 16:05:33,559 ERROR: Task completed with error: 
paragraph text "<para><p>Patient's Name: <strong><em>_</strong><strong></em><em></strong><strong></em><em></strong></em>_</para>" caused exception Parse error: saw </strong> instead of expected </em> [in /Users/didntforeseethat/Revised_PAR/app.py:187]
2024-10-14 16:05:39,550 INFO: Processing route accessed [in /Users/didntforeseethat/Revised_PAR/app.py:164]
2024-10-14 16:05:39,556 INFO: Task state: SUCCESS [in /Users/didntforeseethat/Revised_PAR/app.py:171]
2024-10-14 16:05:39,556 INFO: Task 0f9b84a9-9793-4a0b-b829-7e178e279d1e completed successfully [in /Users/didntforeseethat/Revised_PAR/app.py:179]
2024-10-14 16:05:39,556 ERROR: Task completed with error: 
paragraph text "<para><p>Patient's Name: <strong><em>_</strong><strong></em><em></strong><strong></em><em></strong></em>_</para>" caused exception Parse error: saw </strong> instead of expected </em> [in /Users/didntforeseethat/Revised_PAR/app.py:187]
2024-10-14 16:05:45,544 INFO: Processing route accessed [in /Users/didntforeseethat/Revised_PAR/app.py:164]
2024-10-14 16:05:45,556 INFO: Task state: SUCCESS [in /Users/didntforeseethat/Revised_PAR/app.py:171]
2024-10-14 16:05:45,556 INFO: Task 0f9b84a9-9793-4a0b-b829-7e178e279d1e completed successfully [in /Users/didntforeseethat/Revised_PAR/app.py:179]
2024-10-14 16:05:45,557 ERROR: Task completed with error: 
paragraph text "<para><p>Patient's Name: <strong><em>_</strong><strong></em><em></strong><strong></em><em></strong></em>_</para>" caused exception Parse error: saw </strong> instead of expected </em> [in /Users/didntforeseethat/Revised_PAR/app.py:187]
2024-10-14 16:05:51,543 INFO: Processing route accessed [in /Users/didntforeseethat/Revised_PAR/app.py:164]
2024-10-14 16:05:51,569 INFO: Task state: SUCCESS [in /Users/didntforeseethat/Revised_PAR/app.py:171]
2024-10-14 16:05:51,569 INFO: Task 0f9b84a9-9793-4a0b-b829-7e178e279d1e completed successfully [in /Users/didntforeseethat/Revised_PAR/app.py:179]
2024-10-14 16:05:51,570 ERROR: Task completed with error: 
paragraph text "<para><p>Patient's Name: <strong><em>_</strong><strong></em><em></strong><strong></em><em></strong></em>_</para>" caused exception Parse error: saw </strong> instead of expected </em> [in /Users/didntforeseethat/Revised_PAR/app.py:187]
2024-10-14 16:05:57,541 INFO: Processing route accessed [in /Users/didntforeseethat/Revised_PAR/app.py:164]
2024-10-14 16:05:57,553 INFO: Task state: SUCCESS [in /Users/didntforeseethat/Revised_PAR/app.py:171]
2024-10-14 16:05:57,554 INFO: Task 0f9b84a9-9793-4a0b-b829-7e178e279d1e completed successfully [in /Users/didntforeseethat/Revised_PAR/app.py:179]
2024-10-14 16:05:57,554 ERROR: Task completed with error: 
paragraph text "<para><p>Patient's Name: <strong><em>_</strong><strong></em><em></strong><strong></em><em></strong></em>_</para>" caused exception Parse error: saw </strong> instead of expected </em> [in /Users/didntforeseethat/Revised_PAR/app.py:187]
2024-10-14 16:06:03,539 INFO: Processing route accessed [in /Users/didntforeseethat/Revised_PAR/app.py:164]
2024-10-14 16:06:03,543 INFO: Task state: SUCCESS [in /Users/didntforeseethat/Revised_PAR/app.py:171]
2024-10-14 16:06:03,543 INFO: Task 0f9b84a9-9793-4a0b-b829-7e178e279d1e completed successfully [in /Users/didntforeseethat/Revised_PAR/app.py:179]
2024-10-14 16:06:03,543 ERROR: Task completed with error: 
paragraph text "<para><p>Patient's Name: <strong><em>_</strong><strong></em><em></strong><strong></em><em></strong></em>_</para>" caused exception Parse error: saw </strong> instead of expected </em> [in /Users/didntforeseethat/Revised_PAR/app.py:187]
2024-10-14 20:03:11,505 INFO: PAR application startup [in /Users/didntforeseethat/Revised_PAR/app.py:54]
2024-10-14 20:03:15,617 INFO: Index route accessed [in /Users/didntforeseethat/Revised_PAR/app.py:74]
2024-10-14 20:03:15,618 INFO: Rendering index page [in /Users/didntforeseethat/Revised_PAR/app.py:159]
2024-10-14 20:03:23,237 INFO: Index route accessed [in /Users/didntforeseethat/Revised_PAR/app.py:74]
2024-10-14 20:03:23,240 INFO: POST request received [in /Users/didntforeseethat/Revised_PAR/app.py:76]
2024-10-14 20:03:23,240 INFO: Generated session ID: f9db6737-d694-4bf4-b245-712a19783ac1 [in /Users/didntforeseethat/Revised_PAR/app.py:78]
2024-10-14 20:03:23,240 INFO: Created S3 folder: uploads/f9db6737-d694-4bf4-b245-712a19783ac1/, output folder: ./outputs/f9db6737-d694-4bf4-b245-712a19783ac1 [in /Users/didntforeseethat/Revised_PAR/app.py:83]
2024-10-14 20:03:24,011 INFO: Uploaded file to S3: uploads/f9db6737-d694-4bf4-b245-712a19783ac1/GAD_Results.pdf [in /Users/didntforeseethat/Revised_PAR/app.py:105]
2024-10-14 20:03:24,072 INFO: Verified file exists in S3: uploads/f9db6737-d694-4bf4-b245-712a19783ac1/GAD_Results.pdf [in /Users/didntforeseethat/Revised_PAR/app.py:109]
